# Generated by Django 3.1.7 on 2021-03-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=500, verbose_name='Адрес')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долготоа')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.contact', verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='PetsType',
            fields=[
                ('pets_type', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.hotel', verbose_name='Отель')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('rate', models.FloatField(verbose_name='Цена')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.room', verbose_name='Номер')),
            ],
        ),
    ]
