# Generated by Django 3.1.7 on 2021-04-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название отеля')),
                ('description', models.TextField(blank=True, verbose_name='Описание отеля')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес отеля')),
                ('phone', models.BigIntegerField(blank=True, verbose_name='Номер телефона')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('mass_transport_route', models.TextField(verbose_name='Как добраться на общественном транспорте')),
                ('person_car_route', models.TextField(verbose_name='Как добраться на личном автомобиле')),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=100, verbose_name='Станция метро')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_route', models.CharField(max_length=1000, verbose_name='Путь до фотографии')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='metro',
            field=models.ManyToManyField(to='main_app.Metro'),
        ),
    ]
