# Generated by Django 3.1.7 on 2021-04-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210306_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_app.roomdetail', verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
