# Generated by Django 3.1.7 on 2021-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210421_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание отеля'),
        ),
    ]
