# Generated by Django 3.1.7 on 2021-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_hotel_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Короткое описание отеля'),
        ),
    ]
