# Generated by Django 3.1.7 on 2021-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210421_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro_line', models.CharField(max_length=100, verbose_name='Линия метро')),
                ('img_url', models.TextField(verbose_name='Путь до иконки линии')),
            ],
        ),
        migrations.AddField(
            model_name='metro',
            name='metro_line',
            field=models.ManyToManyField(to='main_app.MetroLine'),
        ),
    ]
