# Generated by Django 3.1.7 on 2021-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210304_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
