# Generated by Django 3.1.7 on 2021-03-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_roomdetail_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='uuid',
        ),
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
